description=Lemmatizer token filter
version=${project.version}
name=opensearch-analysis-lemmagen
classname=org.opensearch.plugin.analysis.lemmagen.AnalysisLemmagenPlugin
java.version=21
opensearch.version=${project.version}
